version: '3.4'

services:
  vite:
    image: vite
    build:
      context: node_modules/vite
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./dist/node/index.js"]
